[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pysitemanagerapi"
version = "0.1.0"
description = "Python client for Offical UniFi Site Manager API"
readme = "README.md"
license = {text = "MIT License"}
requires-python = ">= 3.10"

